# Generated by Django 4.1.5 on 2023-03-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('ciudad', models.CharField(choices=[('caucasia', 'caucasia'), ('cali', 'cali'), ('fusagasuga', 'fusagasuga'), ('sabanalarga', 'sabanalarga'), ('zipaquira', 'zipaquira'), ('leticia', 'leticia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('bogota', 'bogota'), ('cartagena', 'cartagena'), ('cucuta', 'cucuta'), ('girardot', 'girardot'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('turbo', 'turbo'), ('boyaca', 'boyaca'), ('medellin', 'medellin'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('arauca', 'arauca')], max_length=40)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('grado_estudio', models.CharField(choices=[('Especialización_tecnologica', 'Especialización_tecnologica'), ('Especialización_profesional', 'Especialización_profesional'), ('Especialización_tecnica', 'Especialización_tecnica'), ('tecnico', 'tecnico'), ('profesional', 'profesional'), ('tecnologo', 'tecnologo')], max_length=40)),
                ('especialidad', models.CharField(choices=[('Oncología', 'Oncología'), ('Pediatría', 'Pediatría'), ('Cardiología', 'Cardiología'), ('Enfermería_de_familia', 'Enfermería_de_familia'), ('Geriatría', 'Geriatría'), ('Urgencias', 'Urgencias'), ('Atención_primaria', 'Atención_primaria'), ('Salud_escolar', 'Salud_escolar'), ('Nefrología', 'Nefrología'), ('Neonatología', 'Neonatología'), ('Salud_de_la_mujer', 'Salud_de_la_mujer')], max_length=40)),
                ('ciudad', models.CharField(choices=[('caucasia', 'caucasia'), ('cali', 'cali'), ('fusagasuga', 'fusagasuga'), ('sabanalarga', 'sabanalarga'), ('zipaquira', 'zipaquira'), ('leticia', 'leticia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('bogota', 'bogota'), ('cartagena', 'cartagena'), ('cucuta', 'cucuta'), ('girardot', 'girardot'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('turbo', 'turbo'), ('boyaca', 'boyaca'), ('medellin', 'medellin'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('arauca', 'arauca')], max_length=40)),
            ],
            options={
                'db_table': 'profesional',
            },
        ),
        migrations.CreateModel(
            name='soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'soporte',
            },
        ),
    ]
