# Generated by Django 4.1.5 on 2023-03-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('medellin', 'medellin'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('tunja', 'tunja'), ('leticia', 'leticia'), ('apartado', 'apartado'), ('cartagena', 'cartagena'), ('rionegro', 'rionegro'), ('cucuta', 'cucuta'), ('el carmen de bolivar', 'el carmen de bolivar'), ('caucasia', 'caucasia'), ('barranquilla', 'barranquilla'), ('zipaquira', 'zipaquira'), ('turbo', 'turbo'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('arauca', 'arauca'), ('sabanalarga', 'sabanalarga'), ('bogota', 'bogota')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='ciudad',
            field=models.CharField(choices=[('medellin', 'medellin'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('tunja', 'tunja'), ('leticia', 'leticia'), ('apartado', 'apartado'), ('cartagena', 'cartagena'), ('rionegro', 'rionegro'), ('cucuta', 'cucuta'), ('el carmen de bolivar', 'el carmen de bolivar'), ('caucasia', 'caucasia'), ('barranquilla', 'barranquilla'), ('zipaquira', 'zipaquira'), ('turbo', 'turbo'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('arauca', 'arauca'), ('sabanalarga', 'sabanalarga'), ('bogota', 'bogota')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(choices=[('Cardiología', 'Cardiología'), ('Enfermería_de_familia', 'Enfermería_de_familia'), ('Urgencias', 'Urgencias'), ('Salud_de_la_mujer', 'Salud_de_la_mujer'), ('Geriatría', 'Geriatría'), ('Neonatología', 'Neonatología'), ('Nefrología', 'Nefrología'), ('Salud_escolar', 'Salud_escolar'), ('Oncología', 'Oncología'), ('Pediatría', 'Pediatría'), ('Atención_primaria', 'Atención_primaria')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='grado_estudio',
            field=models.CharField(choices=[('profesional', 'profesional'), ('Especialización_tecnologica', 'Especialización_tecnologica'), ('tecnologo', 'tecnologo'), ('tecnico', 'tecnico'), ('Especialización_tecnica', 'Especialización_tecnica'), ('Especialización_profesional', 'Especialización_profesional')], max_length=40),
        ),
    ]
