# Generated by Django 4.1.5 on 2023-03-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_cliente_ciudad_alter_profesional_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('fusagasuga', 'fusagasuga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('girardot', 'girardot'), ('turbo', 'turbo'), ('tunja', 'tunja'), ('leticia', 'leticia'), ('magangue', 'magangue'), ('apartado', 'apartado'), ('caucasia', 'caucasia'), ('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('sabanalarga', 'sabanalarga'), ('cucuta', 'cucuta'), ('facatativa', 'facatativa'), ('bogota', 'bogota'), ('medellin', 'medellin'), ('cali', 'cali'), ('boyaca', 'boyaca'), ('barranquilla', 'barranquilla')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('fusagasuga', 'fusagasuga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('girardot', 'girardot'), ('turbo', 'turbo'), ('tunja', 'tunja'), ('leticia', 'leticia'), ('magangue', 'magangue'), ('apartado', 'apartado'), ('caucasia', 'caucasia'), ('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('sabanalarga', 'sabanalarga'), ('cucuta', 'cucuta'), ('facatativa', 'facatativa'), ('bogota', 'bogota'), ('medellin', 'medellin'), ('cali', 'cali'), ('boyaca', 'boyaca'), ('barranquilla', 'barranquilla')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(choices=[('Salud_escolar', 'Salud_escolar'), ('Cardiología', 'Cardiología'), ('Urgencias', 'Urgencias'), ('Neonatología', 'Neonatología'), ('Geriatría', 'Geriatría'), ('Enfermería_de_familia', 'Enfermería_de_familia'), ('Salud_de_la_mujer', 'Salud_de_la_mujer'), ('Pediatría', 'Pediatría'), ('Nefrología', 'Nefrología'), ('Atención_primaria', 'Atención_primaria'), ('Oncología', 'Oncología')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='grado_estudio',
            field=models.CharField(choices=[('tecnologo', 'tecnologo'), ('Especialización_profesional', 'Especialización_profesional'), ('profesional', 'profesional'), ('Especialización_tecnica', 'Especialización_tecnica'), ('Especialización_tecnologica', 'Especialización_tecnologica'), ('tecnico', 'tecnico')], max_length=40),
        ),
    ]
