# Generated by Django 4.1.5 on 2023-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_cliente_ciudad_alter_profesional_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direcion',
            new_name='direccion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('arauca', 'arauca'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('cali', 'cali'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('medellin', 'medellin'), ('cartagena', 'cartagena'), ('el carmen de bolivar', 'el carmen de bolivar'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('sabanalarga', 'sabanalarga'), ('cucuta', 'cucuta'), ('facatativa', 'facatativa')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('arauca', 'arauca'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('cali', 'cali'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('medellin', 'medellin'), ('cartagena', 'cartagena'), ('el carmen de bolivar', 'el carmen de bolivar'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('sabanalarga', 'sabanalarga'), ('cucuta', 'cucuta'), ('facatativa', 'facatativa')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(choices=[('Neonatología', 'Neonatología'), ('Nefrología', 'Nefrología'), ('Urgencias', 'Urgencias'), ('Atención_primaria', 'Atención_primaria'), ('Cardiología', 'Cardiología'), ('Enfermería_de_familia', 'Enfermería_de_familia'), ('Salud_escolar', 'Salud_escolar'), ('Salud_de_la_mujer', 'Salud_de_la_mujer'), ('Oncología', 'Oncología'), ('Geriatría', 'Geriatría'), ('Pediatría', 'Pediatría')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='grado_estudio',
            field=models.CharField(choices=[('Especialización_tecnica', 'Especialización_tecnica'), ('tecnologo', 'tecnologo'), ('profesional', 'profesional'), ('tecnico', 'tecnico'), ('Especialización_profesional', 'Especialización_profesional'), ('Especialización_tecnologica', 'Especialización_tecnologica')], max_length=40),
        ),
    ]
